### ISSUE TITLE
how to check results

### ISSUE THREAD

**Issue by markvex** [NeuralSec/Daedalus-attack#3]
Hi,
i have tried your project and train your network on a specific image from COCO dataset.
eventually i got few files:
-best example of distortion
-Daedalus example batch .npz
-Distortion of image . npy
-X_adv. npy
-distortions.npy

how can i use them to see the detection before the attack and the final image after the attack?

thanks

**Comment by xubo0321** [comment]
> Hi,
> i have tried your project and train your network on a specific image from COCO dataset.
> eventually i got few files:
> -best example of distortion
> -Daedalus example batch .npz
> -Distortion of image . npy
> -X_adv. npy
> -distortions.npy
> 
> how can i use them to see the detection before the attack and the final image after the attack?
> 
> thanks

@markvex , with the yolov3 to detect the adv images.

**Comment by xubo0321** [comment]
> Hi,
> i have tried your project and train your network on a specific image from COCO dataset.
> eventually i got few files:
> -best example of distortion
> -Daedalus example batch .npz
> -Distortion of image . npy
> -X_adv. npy
> -distortions.npy
> 
> how can i use them to see the detection before the attack and the final image after the attack?
> 
> thanks

@markvex    nothing happened, it also can detect the object correct no matter with the original image and adversarial example.

**Comment by NeuralSec** [comment]
> > Hi,
> > i have tried your project and train your network on a specific image from COCO dataset.
> > eventually i got few files:
> > -best example of distortion
> > -Daedalus example batch .npz
> > -Distortion of image . npy
> > -X_adv. npy
> > -distortions.npy
> > how can i use them to see the detection before the attack and the final image after the attack?
> > thanks
> 
> @markvex nothing happened, it also can detect the object correct no matter with the original image and adversarial example.

Hi Bo, you may try a small fix I posted [here](https://github.com/NeuralSec/Daedalus-attack/issues/2#issuecomment-493829301). Please let me know if the problem is still there after you have applied the fix.

**Comment by NeuralSec** [comment]
Please note that the YOLOv3-416 cfg on the official site is actually having a 608X608 input instead of 416X416. So please change the input dimension to 416x416 in the cfg before testing the adversarial examples.
